yarnPath: .yarn/releases/yarn-3.4.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

# https://stackoverflow.com/questions/67621600/how-do-i-add-shared-dependencies-to-a-monorepo-using-yarn-workspaces
# https://classic.yarnpkg.com/blog/2018/02/15/nohoist/

nodeLinker: node-modules
nmHoistingLimits: "workspaces"
nmSelfReferences: true
