version: '3.5'

x-defaults: &defaults
  env_file:
    - ./.env
    - ./.env.sample
  volumes:
    - ./shared/:/shared
    - ../db/:/db

services:
  backend:
    build:
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    container_name: feed_backend
    ports:
      - 8000:8000
    <<: *defaults
  admin:
    build:
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    container_name: feed_admin
    ports:
      - 8000:8000
